name: PR Code Review Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Send Mail Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com # Şirket SMTP sunucunuz
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[CODE REVIEW BEKLEYEN PR] ${{ github.event.pull_request.title }}"
          to: yetkili@kurum.com
          from: DevSecOps Bot <bot@kurum.com>
          body: |
            Merhaba Yetkili,
            
            Yeni bir Pull Request incelemenizi bekliyor.
            
            PR Başlığı: ${{ github.event.pull_request.title }}
            Açan Kişi: ${{ github.actor }}
            PR Bağlantısı: ${{ github.event.pull_request.html_url }}
            
            Lütfen inceleyip onaylayınız.